name: ad_points
description: 广告积分APP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.0.0
  shared_preferences: ^2.2.0
  flutter_screenutil: ^5.9.0
  flutter_easyloading: ^3.0.5
  image_picker: ^1.0.4
  video_player: ^2.7.2
  intl: ^0.18.1
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.14
  fl_chart: ^0.65.0
  open_file: ^3.3.2
  share_plus: ^7.2.1
  flutter_local_notifications: ^16.3.0
  video_thumbnail: ^0.5.3
  video_compress: ^3.1.2
  qr_flutter: ^4.1.0
  screenshot: ^2.1.0
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 